#!/usr/bin/env python3
"""
generate_redirects.py — Generate public/_redirects from content-inventory.csv.

Produces a Netlify/Cloudflare Pages _redirects file mapping every legacy URL
to its new path, plus pauljab.com catch-all redirect.

Usage:
    python3 scripts/generate_redirects.py
    # Writes to public/_redirects
"""

import csv
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
INVENTORY_CSV = REPO_ROOT / "content-inventory.csv"
REDIRECTS_FILE = REPO_ROOT / "public" / "_redirects"

SKIP_TYPES = {"index", "redirect-only"}

TYPE_TO_BASE = {
    "newsletter":   "/newsletters",
    "book-chapter": "/book",
    "article":      "/articles",
    "poem":         "/poems",
    "book-request": "/book",   # book-request pages redirect to book index
}

GUEST_AUTHOR_SLUG = {
    "rolandpletts":  "roland-pletts",
    "bonniegaunt":   "bonnie-gaunt",
    "kennymitchell": "kenny-mitchell",
    "milesalbright": "miles-albright",
}


def new_url(row):
    content_type = row["type"]
    slug = row["slug"]
    path_parts = Path(row["path"]).parts

    if content_type == "book-request":
        return "/book/"

    if content_type == "guest-author":
        folder = path_parts[0] if len(path_parts) > 1 else ""
        author_slug = GUEST_AUTHOR_SLUG.get(folder, folder)
        filename_slug = slug
        # Index/about pages for an author → /authors/author-slug/
        if path_parts[-1] in ("index.htm", "index.html", "about.htm"):
            return f"/authors/{author_slug}/"
        return f"/authors/{author_slug}/{filename_slug}/"

    base = TYPE_TO_BASE.get(content_type)
    if not base:
        return None

    return f"{base}/{slug}/"


def main():
    rows = list(csv.DictReader(INVENTORY_CSV.open()))

    lines = [
        "# Sonstoglory.com — Legacy URL Redirects",
        "# Generated by scripts/generate_redirects.py",
        "# Format: <old-path>  <new-path>  <status>",
        "",
        "# ── Newsletters ─────────────────────────────────────────────",
    ]

    sections = {
        "newsletter":   ("# ── Newsletters ─────────────────────────────────────────────", []),
        "book-chapter": ("# ── Book chapters ───────────────────────────────────────────", []),
        "article":      ("# ── Articles ────────────────────────────────────────────────", []),
        "guest-author": ("# ── Guest authors ───────────────────────────────────────────", []),
        "book-request": ("# ── Book-request pages → /book/ ─────────────────────────────", []),
        "redirect-only":("# ── Redirect-only stubs ─────────────────────────────────────", []),
    }

    for row in rows:
        content_type = row["type"]
        legacy = row["legacy_url"]

        if content_type in SKIP_TYPES and content_type != "redirect-only":
            continue

        # Special case: redirect-only stub
        if content_type == "redirect-only":
            # 18newmooncelebrations → canonical 18newmonthcelebrations new URL
            target = "/newsletters/18-new-month-celebration/"
            sections["redirect-only"][1].append(f"{legacy}  {target}  301")
            continue

        target = new_url(row)
        if not target:
            continue

        sections[content_type][1].append(f"{legacy}  {target}  301")

    # Build output
    output_lines = [
        "# Sonstoglory.com — Legacy URL Redirects",
        "# Generated by scripts/generate_redirects.py",
        "# Format: <old-path>  <new-path>  301",
        "",
    ]

    for key in ["newsletter", "book-chapter", "article", "guest-author",
                "book-request", "redirect-only"]:
        heading, entries = sections[key]
        if entries:
            output_lines.append(heading)
            output_lines.extend(sorted(entries))
            output_lines.append("")

    # pauljab.com catch-all (add as comment — configured at DNS/hosting level)
    output_lines += [
        "# ── pauljab.com catch-all (configure at host level) ─────────",
        "# /*  https://sonstoglory.com/:splat  301",
        "",
    ]

    content = "\n".join(output_lines)
    REDIRECTS_FILE.write_text(content, encoding="utf-8")
    print(f"Written: {REDIRECTS_FILE}")
    print(f"Total redirect rules: {sum(len(s[1]) for s in sections.values())}")


if __name__ == "__main__":
    main()
